config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: %i[index show]
  devise_for  :users,
              path: '',
              path_names: {
                sign_in: 'login',
                sign_out: 'logout',
                sign_up:  'register'
              }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'react-items', to: 'portfolios#react'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/models/portfolio.rb
# Portfolio Model
class Portfolio < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies,
                                allow_destroy: true,
                                reject_if: lambda { |attrs|
                                  attrs['name'].blank?
                                }

  validates_presence_of :title, :body
  validates :url, :format => URI::regexp(%w(http https))
  validates :github, :format => URI::regexp(%w(http https))

  mount_uploader :thumb_img, PortfolioUploader
  mount_uploader :main_image, PortfolioUploader

  # Creating custom scope... Awesome!!!
  def self.react
    where(subtitle: 'React')
  end

  def self.by_position
    order('position ASC')
  end

  scope :ruby_on_rails_portfolio_items, -> { where(subtitle: 'Ruby on Rails') }
end

app/controllers/portfolios_controller.rb
# Portfolios Controller
class PortfoliosController < ApplicationController
  before_action :set_portfolio_item, only: %i[show edit update destroy]
  layout 'portfolio'
  access all: %i[show index react],
         user: {
           except: %i[destroy new create update edit sort]
         }, site_admin: :all

  def index
    @portfolio_items = Portfolio.by_position
  end

  def sort
    params[:order].each do |key, value|
      Portfolio.find(value[:id]).update(position: value[:position])
    end

    render nothing: true
  end

  def react
    @react_portfolio_items = Portfolio.react
  end

  def show; end

  def new
    @portfolio_item = Portfolio.new
  end

  def edit; end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio_item.save
        format.html {
          redirect_to portfolios_path,
                      notice: 'Your porfolio item is now live.'
        }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html {
          redirect_to portfolios_path,
                      notice: 'The record was successfully updated.'
        }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    # Destroy/delete the record
    @portfolio_item.destroy

    # Redirect
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Record was removed.' }
    end
  end

  private

  def portfolio_params
    params.require(:portfolio).permit(:title,
                                      :subtitle,
                                      :body,
                                      :thumb_img,
                                      :main_image,
                                      :url,
                                      :github,
                                      technologies_attributes:
                                        %i[id name _destroy])
  end

  def set_portfolio_item
    # Perform the lookup
    @portfolio_item = Portfolio.find(params[:id])
  end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
  def image_generator(height:, width:)
    "https://picsum.photos/#{height}/#{width}?random"
  end

  def portfolio_img(img, type)
    if img.model.main_image? || img.model.thumb_img?
      img
    elsif type == 'thumb'
      image_generator(height: '350', width: '200')
    else
      image_generator(height: '600', width: '400')
    end
  end
end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_item) do |f| %>
  <% if @portfolio_item.errors.any? %>
    <% @portfolio_item.errors.full_messages.each do |error| %>
      <%= alert_generator(error) %>
    <% end %>
  <% end %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :subtitle %>
        <%= f.text_field :subtitle, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :github, "Github" %>
        <%= f.text_field :github, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :url, "Web Address" %>
        <%= f.text_field :url, class: "form-control" %>
      </div>
      <div class="form-group">
        <label class="btn btn-primary btn-block">
          Upload a main image file <%= f.file_field :main_image, style: "display:none;" %>
        </label>
      </div>
      <div class="form-group">
        <label class="btn btn-primary btn-block">
          Upload a thumb image file <%= f.file_field :thumb_img, style: "display:none;" %>
        </label>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, class: "form-control", rows: 10 %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <hr>
      <h3>Technologies Used: </h3>
      <div>
        <%= link_to_add_association 'Add technology', f, :technologies %>
      </div>
      <div>
        <%= f.fields_for :technologies do |technology_form| %>
          <%= render  'technology_fields', f: technology_form %>
        <% end %>
      </div>
      <div class="form-group">
        <%= f.submit "Save Item", class: "btn btn-primary btn-block" %>
      </div>
    </div>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="col-md-4">
  <div class="card mb-4 box-shadow" data-id="<%= portfolio_item.id %>">
    <%= image_tag portfolio_img(portfolio_item.thumb_img, 'thumb').to_s, width: '100%', height: '200px' %>
    <div class="card-body">
      <h4><span class="card-text card-title-portfolio">
        <%= link_to portfolio_item.title, portfolio_show_path(portfolio_item), class: "card-img-top" %>
      </span></h4>
      <h6><%= portfolio_item.subtitle %></h6>
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group link-btns">
          <%= link_to  fa_icon("code", text: "View Project"), portfolio_item.url, target: "_blank", class: "btn btn-sm btn-dark" %>
          <%= link_to  fa_icon("github", text: "Github"), portfolio_item.github, target: "_blank", class: "btn btn-sm btn-dark" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/portfolios/_technology_fields.html.erb
<div class="form-group nested-fields">
  <%= f.text_field :name, class: 'form-control', placeholder: 'Tech name...' %>
  <%= link_to_remove_association 'Remove Technology', f %>
</div>

app/views/portfolios/edit.html.erb
<div class="container portfolio-container">
  <h1>Edit Portfolio Item</h1>
  <%= render  "form", portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/index.html.erb
<div class="album py-5 bg-light">
  <div class="container">
    <%= link_to  "New Portfolio Item", new_portfolio_path, class: "btn btn-dark btn-block" if logged_in?(:site_admin) %>
    <hr>
    <%= source_helper('alert alert-warning') %>
    <div class="row <%= "sortable" if logged_in?(:site_admin) %>">
      <%= render partial: 'portfolio_item', collection: @portfolio_items %>
    </div>
  </div>
</div>

app/views/portfolios/new.html.erb
<div class="container portfolio-container">
  <h1>Create a new Portfolio Item</h1>
  <%= render  "form", portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/react.html.erb
<h1>React Portfolio Items</h1>

<%= link_to  "Create New Item", new_portfolio_url if logged_in?(:site_admin) %>

<% @react_portfolio_items.each do |portfolio_item| %>
  <h3><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></h3>

  <p><%= portfolio_item.subtitle %></p>

  <p><%= portfolio_item.body %></p>

  <%= image_tag portfolio_item.thumb_img unless portfolio_item.thumb_img.nil? %>

  <%= link_to  "Edit", edit_portfolio_path(portfolio_item) if logged_in?(:site_admin) %>

  <%= link_to 'Delete Portfolio Item', portfolio_path(portfolio_item),
  method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %>
<% end %>

app/views/portfolios/show.html.erb
<div class="container portfolio-container">
  <div class="row">
    <div class="col-md-7">
      <%= image_tag portfolio_img(@portfolio_item.main_image, 'main').to_s, width: '100%' %>
      <hr>
      <%= link_to  "View All Portfolio Items", portfolios_path, class: "btn btn-primary" %>
      <% if logged_in?(:site_admin) %>
        <%= link_to  "Edit", edit_portfolio_path(@portfolio_item), class: "btn btn-success" %>
      <% end %>
    </div>
    <div class="col-md-5">
      <h1><%= @portfolio_item.title %></h1>
      <em><%= @portfolio_item.subtitle %></em>
      <p><%= @portfolio_item.body %></p>
      <h3>Technologies Used</h3>
      <% @portfolio_item.technologies.each do |t| %>
      <p><%= t.name %></p>
      <% end %>
      <hr>
      <h3>Links to the Outside</h3>
      <div class="btn-group link-btns">
        <%= link_to  fa_icon("code", text: "View Project"), @portfolio_item.url, target: "_blank", class: "btn btn-sm btn-dark" %>
        <%= link_to  fa_icon("github", text: "Github"), @portfolio_item.github, target: "_blank", class: "btn btn-sm btn-dark" %>
      </div>
    </div>
  </div>
</div>