config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: %i[index show]
  devise_for  :users,
              path: '',
              path_names: {
                sign_in: 'login',
                sign_out: 'logout',
                sign_up:  'register'
              }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'react-items', to: 'portfolios#react'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/views/shared/_application_footer.html.erb
<footer class="mastfoot mt-auto">
  <div class="inner">
    <p><%= copyright_generator %></p>
  </div>
</footer>

app/views/shared/_application_nav.html.erb
<header class="masthead mb-auto">
  <div class="inner">
    <a href="/"><h3 class="masthead-brand nav-brand">Brian <span class="last-name">Haltom</span></h3></a>
    <nav class="nav nav-masthead justify-content-center app-nav">
      <%= nav_helper('nav-link', 'span') %>
      <%= login_helper("nav-link") %>
    </nav>
  </div>
</header>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p><%= copyright_generator %></p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title">My Blog</h1>
    <p class="lead blog-description">A blog showcasing my ability to create a blog.</p>
    <span>
      <%= link_to 'Write a New Blog', new_blog_path if logged_in?(:site_admin) %>
    </span> |
    <span>
      <%= link_to 'Topics', topics_path %>
    </span>
  </div>
</div>

app/views/shared/_blog_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light blog-nav mx-auto fixed-top">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="container">
    <%= link_to  "Brian Haltom", root_path, class: "navbar-brand nav-brand" %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <%= nav_helper('nav-link', 'li') %>
        <%= login_helper('nav-link') %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_blog_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4>About</h4>
    <p>I am not a writer. But hey, everyone has a book in them, and maybe mine will start here. Stay tuned!</p>
  </div>

  <%= source_helper("alert alert-info blog-sidebar-source") %>

  <div class="sidebar-module">
    <h4>Topics</h4>
    <% @side_bar_topics.each do |topic| %>
      <p><%= link_to  topic.title, topic_path(topic) %></p>
    <% end %>
  </div>

  <div class="sidebar-module">
    <h4>Elsewhere</h4>
    <ol class="list-unstyled social-links">
      <li><a href="https://github.com/optymystycpryme"><%= fa_icon "github" %></a></li>
      <li><a href="https://www.linkedin.com/in/optymystycpryme/"><%= fa_icon "linkedin" %></a></li>
    </ol>
  </div>
</div>

app/views/shared/_nav.html.erb
<div class="<%= location %>">
  <div><%= link_to  "Home", root_path %></div>
  <div><%= link_to  "About Me", about_me_path %></div>
  <div><%= link_to  "Contact", contact_path %></div>
  <!-- <div><%#= link_to  "Blog", blogs_path %></div> -->
  <div><%= link_to  "Portfolio", portfolios_path %></div>
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container" align="center">
    <p><%= copyright_generator %></p>
  </div>
</footer>

app/views/shared/_portfolio_nav.html.erb
<header class="header">
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">Portfolio Items</h4>
          <p class="text-muted">This is my portfolio album. <br>An awesome collection of my most prized projects. <br>Please feel free to check back often... <br> I'm always working on something new. <br> If you have any questions about the following contents, <br> you can reach me on the contact page. <br>Thanks for visiting!
          </p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Explore</h4>
          <ul class="list-unstyled">
            <%= nav_helper('text-white', 'li') %>
            <li><%= login_helper "text-white" %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark box-shadow">
    <div class="container d-flex justify-content-between">
      <a href="/" class="navbar-brand d-flex align-items-center">
        <h3 class="masthead-brand nav-brand">Brian <span class="last-name">Haltom</span></h3>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader"
        aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>